site_name: Manual Conversion Preview
site_url: http://127.0.0.1:8000
theme:
  name: material
  font: false
  palette:
    primary: custom
  features:
  - navigation.instant
  - navigation.expand
  - navigation.sections
  - search.suggest
  - search.highlight

extra_css:
- stylesheets/base.user.css
- stylesheets/numbered-headings.css

plugins:
  - search:
      lang:
        - en
      separator: '[\s\-]+'
  - add-number:
      order: 2
      strict_mode: false
      excludes:
        - index.md

markdown_extensions:
- attr_list
- admonition
- sane_lists
- pymdownx.details
- pymdownx.superfences
- markdown_callouts
- toc:
    permalink: true
    permalink_title: Link to this section

nav:
  - Home: index.md
  - English:
      - Alarm Communicators:
          - GT Cellular Communicator: manuals/gt-cellular/GT UM_ENG_2025 09 11/index.md
          - GT+ Cellular Communicator: manuals/gt-plus-cellular/GT+ UM_ENG_2025 09 11/index.md
          - GET Cellular Communicator: manuals/get-cellular/GET UM_ENG_2025 09 03/index.md
      - Control Panels:
          - SP3 FLEXi Control Panel: manuals/SP3_TAIM_EN_2025 09 12/index.md
      - Gate Controllers:
          - GATOR Gate Controller: manuals/GATOR_UM_ENG_2025 10 16/index.md
